vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: '%kernel.project_dir%/assets/images'
           upload_destination: '%kernel.project_dir%/public/assets/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true